app/models.py
from . import db
from werkzeug.security import generate_password_hash,check_password_hash
from flask_login import UserMixin
from . import login_manager
from datetime import datetime

@login_manager.user_loader
def load_user(user_id):
    return User.query.get(int(user_id))

class Blog(db.Model):

    __tablename__ = 'blogs'

    id = db.Column(db.Integer,primary_key = True)
    title = db.Column(db.String)
    blog = db.Column(db.String)
    description = db.Column(db.String)
    category = db.Column(db.String, nullable=False)
    comments = db.relationship('Comment', backref='blog', lazy='dynamic')
      #upvotes = db.relationship('Upvote', backref='blog', lazy='dynamic')
      #downvotes = db.relationship('Downvote', backref='blog', lazy='dynamic')
    posted_p = db.Column(db.DateTime,default=datetime.utcnow)
    user_p = db.Column(db.Integer,db.ForeignKey("users.id"),  nullable=False)
    
    
    def save_blog(self):
        db.session.add(self)
        db.session.commit()

    @classmethod
    def get_blog(cls,id):
        blog = Blog.query.order_by(blog_id=id).desc().all()
        return blogs

class Comment(db.Model):

    __tablename__ = 'comments'

    id = db.Column(db.Integer,primary_key = True)
    comment = db.Column(db.String)
    posted_c = db.Column(db.DateTime,default=datetime.utcnow)
    blog_id = db.Column(db.Integer, db.ForeignKey("blogs.id"), nullable=False)
    user_c = db.Column(db.Integer,db.ForeignKey("users.id"), nullable=False)

    def save_comment(self):
        db.session.add(self)
        db.session.commit()

    @classmethod
    def get_comments(cls,id):
        comments = Comments.query.filter_by(blog_id=id).all()
        return comments


class User(UserMixin,db.Model):
    __tablename__ = 'users'

    id = db.Column(db.Integer,primary_key = True)
    username = db.Column(db.String(255),index = True)
    email = db.Column(db.String(255),unique = True,index = True)
    bio = db.Column(db.String(255))
    profile_pic_path = db.Column(db.String())
    password_hash = db.Column(db.String(255))
    blog = db.relationship('Blog', backref='user', lazy='dynamic')
    comment = db.relationship('Comment', backref='user', lazy='dynamic')
      #upvotes = db.relationship('Upvote', backref='user', lazy='dynamic')
      #downvotes = db.relationship('Downvote', backref='user', lazy='dynamic')

    @property
    def password(self):
        raise AttributeError('You cannnot read the password attribute')

    @password.setter
    def password(self, password):
        self.password_hash = generate_password_hash(password)


    def verify_password(self,password):
        return check_password_hash(self.password_hash,password)

    def __repr__(self):
        return f'User {self.username}'


class Quote:
    """
    Adds quote class derived from the API
    """
    def __init__(self, author, quote):
        self.author = author
        self.quote = quote
   

app/main/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField,SubmitField,BooleanField,SubmitField,TextAreaField,RadioField, SelectField
from wtforms.validators import Required

class BlogForm(FlaskForm):
    title = StringField('Blog title', validators = [Required()])
    description = TextAreaField('Blog content', validators = [Required()])
    category = category = SelectField('Select category', choices=[('life-lessons', 'Life lessons'), ('entertainment', 'Entertainment'), ('motivational', 'Motivational')])
    submit = SubmitField('Submit')

class UpdateProfile(FlaskForm):
    bio = TextAreaField('What inspires you??',validators = [Required()])
    submit = SubmitField('Update')

class CommentForm(FlaskForm):
    comment = TextAreaField('Give feedback', validators=[Required()])
    submit = SubmitField('Post')

app/__init__.py
from flask import Flask
from flask_bootstrap import Bootstrap
from flask_sqlalchemy import SQLAlchemy
from flask_login import LoginManager
from config import config_options
from flask_uploads import UploadSet, configure_uploads, IMAGES
from flask_mail import Mail
from flask_simplemde import SimpleMDE


bootstrap = Bootstrap()
bootstrap = Bootstrap()
db = SQLAlchemy()
login_manager = LoginManager()
login_manager.session_protection = 'strong'
login_manager.login_view = 'auth.login'
photos = UploadSet('photos', IMAGES)
mail = Mail()
simple = SimpleMDE()


def create_app(config_name):
    app = Flask(__name__)

    app.config.from_object(config_options[config_name])
    configure_uploads(app, photos)
     #Initializing Flask Extensions
    bootstrap.init_app(app)
    db.init_app(app)
    login_manager.init_app(app)
    mail.init_app(app)
    simple.init_app(app)

    from .main import main as main_blueprint
    app.register_blueprint(main_blueprint)

    from .auth import auth as auth_blueprint
    app.register_blueprint(auth_blueprint,url_prefix = '/authenticate')


    return app

app/main/__init__.py
from flask import Blueprint
main = Blueprint('main' , __name__)
from . import views

app/main/views.py
from . import main
from flask import render_template,request,redirect,url_for, abort
from ..models import Blog, Comment, User, Quote
from flask_login import login_required,current_user
from .. import db, photos
from .forms import BlogForm,UpdateProfile, CommentForm
from ..requests import get_quote

@main.route('/')
def index():

    '''
    View root page function that returns the index page and its data
    '''
    title = 'Home - Welcome to My Blog'
    quote = get_quote()
    return render_template('index.html' , title = title, quote = quote)

@main.route('/<cat>', methods=['GET', 'POST'])
def pickup(cat):
    cat = cat
    blogs = Blog.query.filter_by(category=cat).order_by(Blog.posted_p.desc()).all()
    return render_template('category.html', blogs=blogs)

@main.route('/blog/new', methods = ['GET','POST'])
@login_required
def new_blog():

    form = BlogForm()

    if form.validate_on_submit():
        title = form.title.data
        description = form.description.data
        user_p = current_user
        category = form.category.data

        new_blog = Blog(user_p=current_user._get_current_object().id, title=title, category=category, description = description)

        new_blog.save_blog()
        blogs = Blog.query.filter_by(category=category).order_by(Blog.posted_p.desc()).all()
        return render_template('category.html', blogs=blogs)
    return render_template('new_blog.html', form=form)

@main.route('/comment/new/<int:blog_id>', methods = ['GET','POST'])
@login_required
def new_comment(blog_id):
    form = CommentForm()
    blog = Blog.query.get(blog_id)

    if form.validate_on_submit():
        comment = form.comment.data
         
        # Updated comment instance
        new_comment = Comment(comment=comment,user_c=current_user._get_current_object().id, blog_id=blog_id)

        # save comment method
        new_comment.save_comment()
        return redirect(url_for('.new_comment',blog_id = blog_id ))

    all_comments = Comment.query.filter_by(blog_id=blog_id).all()
    return render_template('comment.html', form=form, comments=all_comments, blog=blog)

@main.route('/myblogs', methods=['GET', 'POST'])
@login_required
def my_blogs():
    user = current_user._get_current_object().id
    blogs = Blog.query.filter_by(user_p=user)
    return render_template('category.html', blogs=blogs)
    

@main.route('/user/<uname>')
def profile(uname):
    user = User.query.filter_by(username = uname).first()

    if user is None:
        abort(404)

    return render_template("profile/profile.html", user = user)

@main.route('/user/<uname>/update',methods = ['GET','POST'])
@login_required
def update_profile(uname):
    user = User.query.filter_by(username = uname).first()
    if user is None:
        abort(404)

    form = UpdateProfile()

    if form.validate_on_submit():
        user.bio = form.bio.data

        db.session.add(user)
        db.session.commit()

        return redirect(url_for('.profile',uname=user.username))

    return render_template('profile/update.html',form =form)

@main.route('/user/<uname>/update/pic',methods= ['POST'])
@login_required
def update_pic(uname):
    user = User.query.filter_by(username = uname).first()
    if 'photo' in request.files: 
        filename = photos.save(request.files['photo'])
        path = f'photos/{filename}'
        user.profile_pic_path = path
        db.session.commit()
    return redirect(url_for('main.index', uname = uname))

app/templates/base.html
<body>
    {% extends 'bootstrap/base.html' %}

    {%block styles %}
    {{super()}}
    <!--Importing the simple mde css and js files  -->
    {{ simplemde.css}}
    {{ simplemde.js }}
    <!-- Font Awesome -->
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css">
    <!-- Bootstrap core CSS -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.3.1/css/bootstrap.min.css" rel="stylesheet">
    <!-- Material Design Bootstrap -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/mdbootstrap/4.7.7/css/mdb.min.css" rel="stylesheet">
    <!-- JQuery -->
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <!-- Bootstrap tooltips -->
    <script type="text/javascript"
        src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.4/umd/popper.min.js"></script>
    <!-- Bootstrap core JavaScript -->
    <script type="text/javascript"
        src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.3.1/js/bootstrap.min.js"></script>
    <!-- MDB core JavaScript -->
    <script type="text/javascript"
        src="https://cdnjs.cloudflare.com/ajax/libs/mdbootstrap/4.7.7/js/mdb.min.js"></script>
    {% endblock %}

    {% block navbar %}
    {% include 'navbar.html' %}
    {% endblock %}


</body>

app/templates/category.html
{% extends 'base.html' %}

{% import 'bootstrap/wtf.html' as wtf %}
{% block styles %}
{{ super() }}
<link rel="stylesheet" href="{{url_for('static', filename='css/index.css')}}">
{% endblock %}


{% block content %}

<div class="body"
    style="background-size:cover;background-repeat: no-repeat ;background-image:url(https://www.google.com/url?sa=i&source=images&cd=&ved=2ahUKEwjNw97w_M_iAhWs4YUKHZ6YBTkQjRx6BAgBEAU&url=https%3A%2F%2Fthemes.shopify.com%2Fthemes%2Flabel%2Fstyles%2Frecord&psig=AOvVaw34iC5ILGYtHbdRIWhDXgf1&ust=1559742679982580)">
    <div class="container" style="background-size:cover;background-repeat: no-repeat ;background-image:url(https://i.pinimg.com/736x/4c/06/d9/4c06d9a333bfb433738891684dc01fc0--paper-backdrop-backdrop-ideas.jpg);">
        <div class="row">
            {% for blog in blogs %}
            <div class="col-md-6">
                <div class="card card-cascade">
                    <div class="view view-cascade gradient-card-header" style= "background-size:cover;background-repeat: no-repeat ;background-image: url(https://www.designyourway.net/blog/wp-content/uploads/2018/01/computer-background-cool-desktop-landscape-lake-desktops-moon-wallpapers-backgrounds-walls-reflection.jpg);">
                        <div class="title text-center">
                            <h2 class="card-header-title mb-3" style="color:white;font-weight: bolder;">{{blog.title}}</h2>
                        </div>
                        <p class="card-header-subtitle mb-0">Category: {{blog.category}}</p>

                    </div>
                    <div class="card-body card-body-cascade text-center">
                        <h4 class=" mb-2 ">{{blog.description}}</h4>
                        <p class="text-right">Posted by :{{blog.user.username}}</p>

                        <hr>

                        <div class=""><a href="{{url_for('main.new_comment',blog_id = blog.id)}}" > View/Give feedback</a>
                        </div>
                    </div>
                    <div class="rounded-bottom mdb-color lighten-3 text-center pt-3">
                        <ul class="list-unstyled list-inline font-small">
                            <li class="list-inline-item pr-2 white-text"><i
                                    class="far fa-clock pr-1"></i>{{blog.posted_p}}</li>
                            <input type=hidden value="{{ next or '' }}" name=next>
                        </ul>
                    </div>
                </div>
                <hr>
            </div>


            {% endfor %}
        </div>

        <a  class= "linkstyle" style="background-color: black;color:white;border-radius: 38px;font-size: 20pt; border-radius:35px; padding: 5px;margin-left: 10%;margin-right: 20%;" href="/blog/new">MAKE YOUR OWN</a>
        {% endblock %}
    </div>
</div>


(% endblock %)

app/templates/comment.html
{% extends 'base.html' %}
{% import 'bootstrap/wtf.html' as wtf %}

{% block content %}
<div class="container">
    {{wtf.quick_form(form)}}

    <div>
        <h3>Comments for {{blog.title}}</h3>
    </div>
    {% if comments %}
    <div class="row text-center" >
        {% for comment in comments %}
        <div class="col-md-4">

            <div class="card" style= "background-color: rgb(201, 197, 197);">
                <div class="card-body">
                    <h4 class="card-title"><a style="color: rgb(151, 22, 22)">{{ comment.comment}}</a></h4>
                    <p class="text-right">Posted by: {{comment.user.username}}</p>
                </div>

            </div>
            <hr>
        </div>
        {% endfor %}
    </div>
    {% else %}

    <h3>No comments</h3>
    {%endif%}

    <a href="/" style="background-color: black;color:white;font-size: 20pt; border-radius:35px; padding: 5px;" >BACK TO CATEGORIES</a>
</div>


{% endblock %}

app/templates/index.html
{% extends 'base.html' %}

{% block styles %}
{{ super() }}
<link rel="stylesheet" href="{{url_for('static', filename='css/index.css')}}">
{% endblock %}

{% block content %}
<div class="container-fluid">
    <div class="jumbotron" style="background-image: url(https://www.designyourway.net/blog/wp-content/uploads/2018/01/computer-background-cool-desktop-landscape-lake-desktops-moon-wallpapers-backgrounds-walls-reflection.jpg);
                                   background-repeat: no-repeat;
                                   background-size: cover">
        <div class="text-white text-center py-5 px-4 my-5">
            <div>
                <h2 class="card-title h1-responsive pt-3 mb-5 font-bold"><strong>Welcome to My Blog</strong></h2>
                <p class="mx-5 mb-5">This is an opportunity to teach other people knowldege that one has acquired...there's no better way to express your ideas and opinions than with a personal blog</p>
                <hr>
                <a class="btn"  style="background-color: white;color:black;border-radius: 38px;" href="/life-lessons">
                    <h4>Life lessons</h4>
                </a>
                <a class="btn" style="background-color: white;color:black;border-radius: 38px;" href="/entertainment">
                    <h4>Entertainment</h4>
                </a>
                <a class="btn" style="background-color: white;color:black;border-radius: 38px;" href="/motivational">
                    <h4>Motivational</h4>
                </a>
                <a class="btn" style="background-color: white;color:black;border-radius: 38px;" href="/blog/new">
                    <h4>New blog</h4>
                </a>
            </div>
        </div>
    </div>
    <!-- Card Dark -->
    <div class="card">

        <div class="view overlay">

            <a>
                <div class="mask rgba-white-slight"></div>
            </a>
        </div>
    </div>
    <!-- Card Dark -->
    <div class= "quotes" style="float:right;margin-left:50%;color: white;background-color: rgb(88, 53, 29);border-radius: 30px;">
        <h4 style= "text-align: center;"><u>Get inspired</u></h4>
        <p class="quote-text " style="font-weight: bolder; font-size:10pt;;"> 
            {{quote.quote}}
          </p>
          <hr />
          <div class="quotes">
            <p class="custom">
             ~ {{quote.author}} ~
            </p>
        </div>
    </div>
   
</div>
<br>
<br>
<hr>
    <!-- Copyright info-->
    <div class="footer-copyright text-center py-3" style="background-color:rgb(0, 0, 0);border-radius: 38px;margin-left:40%;margin-right:40%">© 2020 Copyright:
        <a href="https://github.com/nairdaee" style="color:blanchedalmond"> Adrian Etenyi</a>
    </div>
    <!-- Copyright info-->


{% endblock %}   
                                   </div>
</div>

app/templates/navbar.html
<nav class="navbar navbar-expand-lg navbar-light" style= "background-color:black;border-radius: 0px;">
    <a class="navbar-brand" href="/"> </a>

    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#basicExampleNav"
        aria-controls="basicExampleNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="basicExampleNav">

        <ul class="navbar-nav mr-auto">
          
            <li class="nav-item">
                <a class="nav-link" href="/myblogs">
                    <h4 style = "color:aliceblue;">My blogs</h4>
                </a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="/blog/new">
                    <h4 style = "color:aliceblue;">Add blog</h4>
                </a>
            </li>

            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" id="navbarDropdownMenuLink" data-toggle="dropdown"
                    aria-haspopup="true" aria-expanded="false">
                    <h4 style = "color:aliceblue;">Categories</h4>
                </a>
                <div class="dropdown-menu dropdown-primary" aria-labelledby="navbarDropdownMenuLink" style="color: white">
                    <a class="dropdown-item" href="/entertainment">Entertainment</a>
                    <a class="dropdown-item" href="/motivational">Motivational</a>
                    <a class="dropdown-item" href="/life-lessons">Life lessons</a>
                </div>
            </li>

        </ul>
        <ul class="navbar-nav ml-auto">
            <li class="nav-item">
                <a class="nav-link" href="/"><i class="fas fa-home fa-3x black" style= "background-color:black;color:blanchedalmond;border-radius: 20px"></i>
                </a>
            </li>
            <li><a class="nav-link" href="{{url_for('main.profile',uname=current_user.username)}}"><i
                        class="fas fa-chalkboard-teacher fa-3x" style="color:white"></i>
                    <p style="color:white">Profile</p>
                </a></li>
            <li><a class="nav-link" href="{{url_for('auth.login')}}"><i class="fas fa-sign-in-alt fa-3x" style="color:white"></i>
                    <p style="color:white">Sign in</p>
                </a></li>
            <li><a class="nav-link" href="{{url_for('auth.logout')}}"><i class="fas fa-sign-out-alt fa-3x" style="color:white"></i>
                    <p style="color:white">Sign out</p>
                </a></li>


        </ul>

</nav>

app/templates/new_blog.html
{% extends 'base.html' %}
{% import 'bootstrap/wtf.html' as wtf %}

{% block styles %}
{{ super() }}
<link rel="stylesheet" href="{{url_for('static', filename='css/index.css')}}">
{% endblock %}

{% block content %}
<div class="container">
    {{wtf.quick_form(form)}}
</div>

    <!-- Copyright -->
    <div class="footer-copyright text-center py-3">© 2019 Copyright:
        <a href="#"> Adrian Etenyi</a>
    </div>
    <!-- Copyright -->

{% endblock %}

app/templates/profile/profile.html
{% extends 'base.html'%}

{% block content %}

<div class="container">

<div class="row">


  <div class="col-md-4">
    <h3> {{user.username| capitalize}} </h3>

    {% if user.bio %}
      <p> {{user.bio}}</p>

    {%else%}
      <p> {{user.username| capitalize}} has no bio </p>
    {% endif %}

    {% if user == current_user %}
      <a href="{{url_for('main.update_profile',uname=user.username)}}">Edit profile</a>
    {% endif %}
    <br>
    <br>
    <br>
    <br>
    <a href="/" style="background-color: black;color:white;border-radius: 38px;padding: 5px;" >DONE</a>
  </div>
  <div class="col-md-4">
    {% if user.profile_pic_path %}

    <img src="{{url_for('static',filename=user.profile_pic_path)}}" alt="" class="img-thumbnail">

    {%else%}
    <p>No profile picture</p>

    {% endif %}
        {% if user == current_user %}
    <form  action="{{url_for('main.update_pic',uname=user.username)}}" method="post" enctype = "multipart/form-data">

      <input type="file"  name="photo" class="form-control" required>
      <input type="submit"> 
    </form>
      {% endif %}
  </div>


</div>
</div>
{% endblock %}

app/templates/profile/update.html
{% extends 'base.html' %}
{% import 'bootstrap/wtf.html' as wtf %}

{% block content %}
<div class="container">
  {{wtf.quick_form(form)}}
</div>
{% endblock %}